id: P005599
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:06:01.296444
source_metadata:
  id: bdr:W3CN4693
  title: མཁས་དབང་ཚུལ་ཁྲིམས་བློ་གྲོས་ཀྱི་འཆད་ཁྲིད་མཐའ་གཉིས་རབ་གསལ།
  author: ''
  volumes:
    a5390fc30a4b40c3938ec917a056e65c:
      image_group_id: I3CN4695
      title: ''
      volume_number: 1
      total_pages: 222
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
