id: P005599
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4693
  title: མཁས་དབང་ཚུལ་ཁྲིམས་བློ་གྲོས་ཀྱི་འཆད་ཁྲིད་མཐའ་གཉིས་རབ་གསལ།
  author: ''
  volumes:
    a5390fc30a4b40c3938ec917a056e65c:
      image_group_id: I3CN4695
      title: ''
      volume_number: 1
      total_pages: 222
      base_file: v001.txt
